CREATE DATABASE DangKyPhuongTien;
USE DangKyPhuongTien;

CREATE TABLE nhacungcap(
MaNhaCC VARCHAR(20) PRIMARY KEY,
TenNhaCC VARCHAR(30),
DiaChi VARCHAR(30),
SoDT VARCHAR(20),
MaSoThue VARCHAR(20)
);
CREATE TABLE loaidichvu(
MaLoaiDV VARCHAR(20) PRIMARY KEY,
TenLoaiDV VARCHAR(20)
);
ALTER TABLE loaidichvu MODIFY TenLoaiDV VARCHAR(60);
CREATE TABLE mucphi(
MaMP VARCHAR(20) PRIMARY KEY,
DonGia INT,
MoTa VARCHAR(30)
);
CREATE TABLE dongxe(
DongXe VARCHAR(20) PRIMARY KEY,
HangXe VARCHAR(40),
SoChoNgoi INT
);
CREATE TABLE dangkycungcap(
MaDKCC VARCHAR(20) PRIMARY KEY,
MaNhaCC VARCHAR(20),
MaLoaiDV VARCHAR(20),
DongXe VARCHAR(20),
MaMP VARCHAR(20),
NgayBatDauCungCap DATE,
NgayKetThucCungCap DATE,
FOREIGN KEY(MaNhaCC) REFERENCES nhacungcap(MaNhaCC),
FOREIGN KEY(MaLoaiDV) REFERENCES loaidichvu(MaLoaiDV),
FOREIGN KEY(DongXe) REFERENCES dongxe(DongXe),
FOREIGN KEY(MaMP) REFERENCES mucphi(MaMP)
);